### ISSUE TITLE
improve the performance

### ISSUE THREAD

**Issue by taogashi** [mblum/libgp#13]
I've run the example, found that it takes more than 10 secs to process, most in add_pattern.
I'm not quite familiar with gaussian process, and wonder if it is possible to improve the performance.

**Comment by mblum** [comment]
GPs have cubic run time in the number of samples. We do quick updates after each time a new pattern is added, but you could also implement it in a way, that everything is updated in one batch after all patterns are added. For me it didn't make a difference in the total time spent.
