### ISSUE TITLE
issues with make file 

### ISSUE THREAD

**Issue by andrewcz** [mblum/libgp#14]
hi awesome library 

i am trying to build it but get 

andrewcz@andrewcz-PORTEGE-Z30t-B ~ $ cmake ../andrewcz/libgp/
-- The CXX compiler identification is GNU 4.8.5
-- The C compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK)
  (Required is at least version "3.0.1")
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  FindEigen3.cmake:77 (find_package_handle_standard_args)
  CMakeLists.txt:21 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/home/andrewcz/CMakeFiles/CMakeOutput.log".

would you have some advice.

Best,
Andrew

**Comment by mblum** [comment]
Hi Andrew,

according to the error message you don't have Eigen3 installed. Install it with your package manager and Cmake should be able to find it.

Best
Manuel
